services:
  chromadb:
    image: chromadb/chroma:1.1.1
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/chroma_sentence:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - ./volumes/es-data:/usr/share/elasticsearch/data

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

    volumes:
      - ./volumes/kafka-data:/bitnami/kafka

  api:
    platform: linux/amd64
    build: ./bff
    container_name: fastapi-api
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=collect-events
      - CHROMA_HOST=http://chromadb:8000
      - CHROMA_COLLECTION_NAME=korean_sentences
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - chromadb
      - elasticsearch
      - kafka

  collector:
    build: ./collector
    container_name: collector
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=collect-events
      - CSV_PATH=/data/grammar_errors.csv
    volumes:
      - ./volumes/new-error-data:/data
    depends_on:
      - kafka
