services:
  chromadb-sentence:
    image: chromadb/chroma:1.1.1
    container_name: chromadb-sentence
    ports:
      - "8000:8000"
    volumes:
      - volumes/chroma_sentence:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - volumes/es-data:/usr/share/elasticsearch/data

  kafka:
    image: bitnami/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - volumes/kafka-data:/bitnami/kafka

  api:
    build: ./bff
    container_name: fastapi-api
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=collect-events
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - CHROMA_SENTENCE_HOST=http://chromadb-sentence:8000
    depends_on:
      - chromadb-sentence
      - elasticsearch
      - kafka

  collector:
    build: ./collector
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=collect-events
      - CSV_PATH=/data/grammar_errors.csv
    volumes:
      - volumes/new-error-data:/data
    depends_on:
      - kafka
